# Generated by Django 4.2.4 on 2023-08-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    # Зависимости
    dependencies = [
    ]

    # Операции
    operations = [
        migrations.CreateModel(
            name='Adverisements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('auction', models.BooleanField(default=False, verbose_name='Торг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновлния')),
            ],
        ),
    ]
