# Generated by Django 4.2.4 on 2023-08-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('App', '0002_alter_adverisements_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverisements',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
