# Generated by Django 4.2.4 on 2023-08-21 23:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('App', '0003_alter_adverisements_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adverisements',
            table=None,
        ),
    ]
