# Generated by Django 4.2.4 on 2023-08-22 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('App', '0004_alter_adverisements_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adverisements',
            table='advertisements',
        ),
    ]
