# Generated by Django 4.2.4 on 2023-08-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('App', '0005_alter_adverisements_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverisements',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
