# Generated by Django 4.2.4 on 2023-08-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('App', '0007_adverisements_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverisements',
            name='image',
            field=models.ImageField(default='', upload_to='adverisements/', verbose_name='Изоюражения'),
            preserve_default=False,
        ),
    ]
